version: '3.8'

services:
  wiki-server:
    build: ./server
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :80 --workers 4 --threads 100 manage:app
    env_file:
      - ./.env
    depends_on:
      - wiki-db
    labels:
      - traefik.http.routers.monsiteweb.rule=Host(`api.wiki-wars.fr`)
      - traefik.http.routers.monsiteweb.tls=true
      - traefik.http.routers.monsiteweb.tls.certresolver=lets-encrypt
      - traefik.port=80

  wiki-client:
    build: ./client
    command: nginx -g "daemon off;"
    labels:
      - traefik.http.routers.monsiteweb.rule=Host(`wiki-wars.fr`)
      - traefik.http.routers.monsiteweb.tls=true
      - traefik.http.routers.monsiteweb.tls.certresolver=lets-encrypt
      - traefik.port=80

  wiki-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
      - ./.env.${ENV}.db
    labels:
      - traefik.http.routers.monsiteweb.rule=Host(`wiki-wars.fr`)
      - traefik.port=80

volumes:
  postgres_data: