version: '3.8'

services:
  wiki-server:
    build: ./server
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :5000 --workers 4 --threads 100 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - wiki-db
    labels:
      - "traefik.http.routers.wiki-server.rule=Host(`api.wiki-wars.fr`)"

  wiki-client:
    build: ./client
    command: nginx -g "daemon off;"
    ports:
      - 80:80
    labels:
      - "traefik.http.routers.wiki-client.rule=Host(`wiki-wars.fr`)"

  wiki-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
      - ./.env.${ENV}.db
    labels:
      - "traefik.http.routers.wiki-db.rule=Host(`wiki-wars.fr`)"

volumes:
  postgres_data: