version: '3.8'

services:
  wiki-server:
    build: ./server
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b 0.0.0.0:5000 --workers 1 --threads 400 manage:app
    env_file:
      - ./.env
    depends_on:
      - wiki-db
    expose:
      - 5000
    labels:
      - traefik.http.routers.wiki-server.rule=Host(`api.wiki-wars.fr`)
      - traefik.http.routers.wiki-server.tls=true
      - traefik.http.routers.wiki-server.tls.certresolver=lets-encrypt
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.http.services.wiki-server.loadbalancer.server.port=5000
    networks:
      - web

  wiki-client:
    build: ./client
    command: nginx -g "daemon off;"
    labels:
      - traefik.http.routers.wiki-client.rule=Host(`wiki-wars.fr`)
      - traefik.http.routers.wiki-client.tls=true
      - traefik.http.routers.wiki-client.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web

  wiki-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
      - ./.env.${ENV}.db
    labels:
      - traefik.tcp.routers.wiki-db.entrypoints=bdd
      - traefik.tcp.routers.wiki-db.rule=HostSNI(`wiki-wars.fr`)
      - traefik.tcp.routers.wiki-db.service=wiki-db
      - traefik.tcp.services.wiki-db.loadbalancer.server.port=5432
    networks:
      - web

volumes:
  postgres_data:

networks:
    web:
      external: true