version: '3.8'

services:
  wiki-server:
    build: ./server
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :80 --workers 4 --threads 100 manage:app
    env_file:
      - ./.env
    depends_on:
      - wiki-db
    labels:
      - traefik.http.routers.wiki-server.rule=Host(`api.wiki-wars.fr`)
      - traefik.http.routers.wiki-server.tls=true
      - traefik.http.routers.wiki-server.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web

  wiki-client:
    build: ./client
    command: nginx -g "daemon off;"
    labels:
      - traefik.http.routers.wiki-client.rule=Host(`wiki-wars.fr`)
      - traefik.http.routers.wiki-client.tls=true
      - traefik.http.routers.wiki-client.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web

  wiki-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
      - ./.env.${ENV}.db
    labels:
      - traefik.http.routers.wiki-db.rule=Host(`wiki-wars.fr`)
      - traefik.port=5432
    networks:
      - web

volumes:
  postgres_data:

networks:
    web:
      external: true
    internal:    
      external: false