"""empty message

Revision ID: 237a98dc01fa
Revises: 579ea334c13c
Create Date: 2023-06-27 01:02:40.854332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237a98dc01fa'
down_revision = '579ea334c13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('validation_token', sa.Uuid(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('validation_token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
