"""empty message

Revision ID: 589eb7436e45
Revises: 4d40547e63f3
Create Date: 2023-02-28 23:53:15.000057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589eb7436e45'
down_revision = '4d40547e63f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
