"""empty message

Revision ID: 6310cc378d3d
Revises: d70bcd855011
Create Date: 2023-03-04 22:27:15.965867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6310cc378d3d'
down_revision = 'd70bcd855011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_host_id_users', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_games_host_id_users', 'users', ['host_id'], ['id'])

    # ### end Alembic commands ###
