"""empty message

Revision ID: 639edaccc099
Revises: 237a98dc01fa
Create Date: 2023-06-27 01:11:07.924355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639edaccc099'
down_revision = '237a98dc01fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_email', ['email'])
        batch_op.create_unique_constraint('uix_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_username', type_='unique')
        batch_op.drop_constraint('uix_user_email', type_='unique')

    # ### end Alembic commands ###
