"""empty message

Revision ID: 7056197d5160
Revises: 1f6f52c3d1da
Create Date: 2023-08-07 13:37:08.664947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7056197d5160'
down_revision = '1f6f52c3d1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sid')

    # ### end Alembic commands ###
