"""empty message

Revision ID: 917f50d65e4c
Revises: 589eb7436e45
Create Date: 2023-03-01 00:23:07.204482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917f50d65e4c'
down_revision = '589eb7436e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_winner_id_users'), 'users', ['winner_id'], ['id'])
        batch_op.drop_column('winner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_games_winner_id_users'), type_='foreignkey')
        batch_op.drop_column('winner_id')

    # ### end Alembic commands ###
