"""empty message

Revision ID: af498f7b206f
Revises: 3b2229d2cae4
Create Date: 2023-03-04 22:17:15.943426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af498f7b206f'
down_revision = '3b2229d2cae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_host_id_users'), 'users', ['host_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_host_id_users'), type_='foreignkey')
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
