"""empty message

Revision ID: d70bcd855011
Revises: af498f7b206f
Create Date: 2023-03-04 22:17:43.704427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70bcd855011'
down_revision = 'af498f7b206f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
