name: Build&Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build & Deploy
        run: cp ~/Wikiwars/.env.prod.db ~/actions-runner/_work/Wikiwars/Wikiwars/ && sudo docker compose up -d --build
