name: Build&Deploy

on: workflow_dispatch

jobs:
  setup:
    runs-on: self-hosted
    environment: PROD
    steps:
      - name: Pull Project
        uses: actions/checkout@v4.1.1
      - name: Setup environment
        env:
          ENV: ${{ secrets.ENV }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: chmod u+x scripts/deploy.sh && ./scripts/deploy.sh
  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Build docker services
        run: sudo docker compose build
  create:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Create docker containers
        run: sudo docker compose create
  deploy:
    runs-on: self-hosted
    needs: create
    steps:
      - name: Start containers
        run: sudo docker compose start
