name: Build&Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: self-hosted
    environment: PROD
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build & Deploy
        env:
          ENV: ${{ secrets.ENV }}
        run: echo "$ENV" >> test.txt
